spring:
  datasource:
    username: root
    password: handhand
    url: jdbc:mysql://127.0.0.1:3306/mt_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 3
    minIdle: 3
    maxActive: 10
